-- MySQL Script generated by MySQL Workbench
-- 10/04/15 11:16:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hsts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hsts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hsts` DEFAULT CHARACTER SET utf8 ;
USE `hsts` ;

-- -----------------------------------------------------
-- Table `hsts`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`Role` (
  `roleID` INT(11) NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`account` (
  `accountID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fullName` VARCHAR(45) NULL DEFAULT NULL,
  `roleID` INT(11) NOT NULL,
  `status` INT NULL,
  `dateOfBirth` DATE NULL,
  PRIMARY KEY (`accountID`),
  INDEX `fk_account_role_idx` (`roleID` ASC),
  CONSTRAINT `fk_account_role`
    FOREIGN KEY (`roleID`)
    REFERENCES `hsts`.`Role` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`doctor` (
  `doctorID` INT NOT NULL AUTO_INCREMENT,
  `accountID` INT NOT NULL,
  `major` VARCHAR(45) NULL,
  PRIMARY KEY (`doctorID`),
  INDEX `fk_doctor_account1_idx` (`accountID` ASC),
  CONSTRAINT `fk_doctor_account1`
    FOREIGN KEY (`accountID`)
    REFERENCES `hsts`.`account` (`accountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`food` (
  `foodID` INT(11) NOT NULL AUTO_INCREMENT,
  `foodName` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`foodID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`regimen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`regimen` (
  `regimenID` INT(11) NOT NULL AUTO_INCREMENT,
  `illnessName` VARCHAR(45) NULL,
  PRIMARY KEY (`regimenID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`patient` (
  `patientID` INT NOT NULL AUTO_INCREMENT,
  `accountID` INT NOT NULL,
  `wristbandID` VARCHAR(45) NULL,
  `status` INT NULL,
  PRIMARY KEY (`patientID`),
  INDEX `fk_patient_account1_idx` (`accountID` ASC),
  CONSTRAINT `fk_patient_account1`
    FOREIGN KEY (`accountID`)
    REFERENCES `hsts`.`account` (`accountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`medical_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`medical_record` (
  `medical_recordID` INT(11) NOT NULL AUTO_INCREMENT,
  `regimenID` INT NOT NULL,
  `doctorID` INT NOT NULL,
  `patientID` INT NOT NULL,
  `patient_account_Username` VARCHAR(25) NOT NULL,
  `startTime` DATE NOT NULL,
  `status` INT NULL,
  `medicalHistory` VARCHAR(200) NULL,
  `clinicalSymptoms` VARCHAR(200) NULL,
  PRIMARY KEY (`medical_recordID`),
  INDEX `fk_medical_record_regimen_idx` (`regimenID` ASC),
  INDEX `fk_medical_record_Doctor1_idx` (`doctorID` ASC),
  INDEX `fk_medical_record_patient1_idx` (`patientID` ASC),
  CONSTRAINT `fk_medical_record_regimen`
    FOREIGN KEY (`regimenID`)
    REFERENCES `hsts`.`regimen` (`regimenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_record_Doctor1`
    FOREIGN KEY (`doctorID`)
    REFERENCES `hsts`.`doctor` (`doctorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_record_patient1`
    FOREIGN KEY (`patientID`)
    REFERENCES `hsts`.`patient` (`patientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`appointment` (
  `appointmentID` INT NOT NULL AUTO_INCREMENT,
  `appointmentDateTime` DATETIME(1) NULL,
  `appointmentMessage` VARCHAR(200) NULL,
  `status` INT NULL,
  `medical_recordID` INT NULL,
  PRIMARY KEY (`appointmentID`),
  INDEX `fk_appointment_medicalrecord_idx` (`medical_recordID` ASC),
  CONSTRAINT `fk_appointment_medicalrecord`
    FOREIGN KEY (`medical_recordID`)
    REFERENCES `hsts`.`medical_record` (`medical_recordID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`medical_record_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`medical_record_data` (
  `medical_record_dataID` INT(11) NOT NULL AUTO_INCREMENT,
  `height` INT(11) NULL DEFAULT NULL,
  `weight` INT(11) NULL DEFAULT NULL,
  `numberOfStep` INT(11) NULL DEFAULT NULL,
  `calories` INT(11) NULL DEFAULT NULL,
  `distance` FLOAT NULL,
  `dateCollectData` DATE NULL,
  `appointmentID` INT NOT NULL,
  `type` INT NULL,
  PRIMARY KEY (`medical_record_dataID`),
  INDEX `fk_data_appointment_idx` (`appointmentID` ASC),
  CONSTRAINT `fk_data_appointment`
    FOREIGN KEY (`appointmentID`)
    REFERENCES `hsts`.`appointment` (`appointmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`medicine` (
  `medicineID` INT(11) NOT NULL AUTO_INCREMENT,
  `MedicineName` VARCHAR(45) NULL DEFAULT NULL,
  `Producer` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`medicineID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`Treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`Treatment` (
  `treatmentID` INT NOT NULL AUTO_INCREMENT,
  `fromDate` DATE NOT NULL,
  `toDate` DATE NOT NULL,
  `appointientID` INT NOT NULL,
  `advise` VARCHAR(400) NULL,
  PRIMARY KEY (`treatmentID`),
  INDEX `fk_treatement_appointment_idx` (`appointientID` ASC),
  CONSTRAINT `fk_treatement_appointment`
    FOREIGN KEY (`appointientID`)
    REFERENCES `hsts`.`appointment` (`appointmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`medicine_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`medicine_time` (
  `medicine_timeID` INT NOT NULL AUTO_INCREMENT,
  `timeUse` TIME NULL,
  `treatmentID` INT NULL,
  PRIMARY KEY (`medicine_timeID`),
  INDEX `fk_medicine_time_treatment_idx` (`treatmentID` ASC),
  CONSTRAINT `fk_medicine_time_treatment`
    FOREIGN KEY (`treatmentID`)
    REFERENCES `hsts`.`Treatment` (`treatmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`medicine_treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`medicine_treatment` (
  `medicine_treatmentID` INT(11) NOT NULL AUTO_INCREMENT,
  `medicineID` INT(11) NULL DEFAULT NULL,
  `numberOfMedicine` FLOAT NULL DEFAULT NULL,
  `medicine_timeID` INT NULL,
  PRIMARY KEY (`medicine_treatmentID`),
  INDEX `fk_medicine_treatment_medicine_idx` (`medicineID` ASC),
  INDEX `fk_medicine_treatment_medicineTime_idx` (`medicine_timeID` ASC),
  CONSTRAINT `fk_medicine_treatment_medicine`
    FOREIGN KEY (`medicineID`)
    REFERENCES `hsts`.`medicine` (`medicineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicine_treatment_medicineTime`
    FOREIGN KEY (`medicine_timeID`)
    REFERENCES `hsts`.`medicine_time` (`medicine_timeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`phase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`phase` (
  `phaseID` INT(11) NOT NULL AUTO_INCREMENT,
  `fromdate` INT NULL DEFAULT NULL,
  `todate` INT NULL,
  `regimenID` INT(11) NOT NULL,
  PRIMARY KEY (`phaseID`),
  INDEX `fk_phase_regimen1_idx` (`regimenID` ASC),
  CONSTRAINT `fk_phase_regimen1`
    FOREIGN KEY (`regimenID`)
    REFERENCES `hsts`.`regimen` (`regimenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`practice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`practice` (
  `practiceID` INT(11) NOT NULL AUTO_INCREMENT,
  `practiceName` VARCHAR(45) NULL DEFAULT NULL,
  `intensity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`practiceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hsts`.`meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`meal` (
  `mealID` INT NOT NULL AUTO_INCREMENT,
  `treatmentID` INT NULL,
  `timeStart` TIME NULL,
  PRIMARY KEY (`mealID`),
  INDEX `fk_meal_treatment_idx` (`treatmentID` ASC),
  CONSTRAINT `fk_meal_treatment`
    FOREIGN KEY (`treatmentID`)
    REFERENCES `hsts`.`Treatment` (`treatmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`food_treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`food_treatment` (
  `food_treatmentID` INT NOT NULL AUTO_INCREMENT,
  `foodID` INT NULL,
  `quantitative` VARCHAR(45) NULL,
  `mealID` INT NULL,
  PRIMARY KEY (`food_treatmentID`),
  INDEX `fk_food_treatment_food_idx` (`foodID` ASC),
  INDEX `fk_food_treatment_meal_idx` (`mealID` ASC),
  CONSTRAINT `fk_food_treatment_food`
    FOREIGN KEY (`foodID`)
    REFERENCES `hsts`.`food` (`foodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_treatment_meal`
    FOREIGN KEY (`mealID`)
    REFERENCES `hsts`.`meal` (`mealID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`practice_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`practice_time` (
  `practicetimeID` INT NOT NULL AUTO_INCREMENT,
  `timeStart` TIME NULL,
  `treatmentID` INT NULL,
  PRIMARY KEY (`practicetimeID`),
  INDEX `fk_practice_time_treatment_idx` (`treatmentID` ASC),
  CONSTRAINT `fk_practice_time_treatment`
    FOREIGN KEY (`treatmentID`)
    REFERENCES `hsts`.`Treatment` (`treatmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`practice_treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`practice_treatment` (
  `practice_treatmentID` INT NOT NULL AUTO_INCREMENT,
  `practiceID` INT NULL,
  `timeDuration` INT NULL,
  `practice_timeID` INT NULL,
  PRIMARY KEY (`practice_treatmentID`),
  INDEX `fk_practice_treatment_practice_idx` (`practiceID` ASC),
  INDEX `fk_practice_treatment_practiceTime_idx` (`practice_timeID` ASC),
  CONSTRAINT `fk_practice_treatment_practice`
    FOREIGN KEY (`practiceID`)
    REFERENCES `hsts`.`practice` (`practiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_practice_treatment_practiceTime`
    FOREIGN KEY (`practice_timeID`)
    REFERENCES `hsts`.`practice_time` (`practicetimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`device` (
  `deviceID` INT NOT NULL AUTO_INCREMENT,
  `brandName` VARCHAR(45) NULL,
  `brandUUID` VARCHAR(45) NULL,
  `numberOfStepUUID` VARCHAR(45) NULL,
  `positionNumberOfStep` INT NULL,
  PRIMARY KEY (`deviceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`food_phase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`food_phase` (
  `food_phaseID` INT NOT NULL AUTO_INCREMENT,
  `phaseID` INT NULL,
  `foodID` INT NULL,
  PRIMARY KEY (`food_phaseID`),
  INDEX `fk_phase_food_idx` (`phaseID` ASC),
  INDEX `fk_phase_food_food_idx` (`foodID` ASC),
  CONSTRAINT `fk_phase_food_phase`
    FOREIGN KEY (`phaseID`)
    REFERENCES `hsts`.`phase` (`phaseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phase_food_food`
    FOREIGN KEY (`foodID`)
    REFERENCES `hsts`.`food` (`foodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`medicine_phase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`medicine_phase` (
  `medicine_phaseID` INT NOT NULL AUTO_INCREMENT,
  `phaseID` INT NULL,
  `medicineID` INT NULL,
  PRIMARY KEY (`medicine_phaseID`),
  INDEX `fk_medicine_phase_phase_idx` (`phaseID` ASC),
  INDEX `fk_medicine_phase_medicine_idx` (`medicineID` ASC),
  CONSTRAINT `fk_medicine_phase_phase`
    FOREIGN KEY (`phaseID`)
    REFERENCES `hsts`.`phase` (`phaseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicine_phase_medicine`
    FOREIGN KEY (`medicineID`)
    REFERENCES `hsts`.`medicine` (`medicineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsts`.`practice_phase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsts`.`practice_phase` (
  `practice_phaseID` INT NOT NULL AUTO_INCREMENT,
  `phaseID` INT NULL,
  `practiceID` INT NULL,
  PRIMARY KEY (`practice_phaseID`),
  INDEX `fk_practice_phase_phase_idx` (`phaseID` ASC),
  INDEX `fk_practice_phase_practice_idx` (`practiceID` ASC),
  CONSTRAINT `fk_practice_phase_phase`
    FOREIGN KEY (`phaseID`)
    REFERENCES `hsts`.`phase` (`phaseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_practice_phase_practice`
    FOREIGN KEY (`practiceID`)
    REFERENCES `hsts`.`practice` (`practiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
